apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-argocd-test-app
  namespace: argocd # for argocd application management
spec:
  project: default
  source:
    repoURL: https://github.com/Norriswu266/helm-argocd-test
    targetRevision: main
    path: . # chart location
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc #Target K8S endpoint, for example: https://ABCD1234.gr7.ap-northeast-1.eks.amazonaws.com
    namespace: demo-app # target k8s resource namespace (multi namespace from source should create another argocd applications)